import { DateRangePicker } from "@/components/reports/DateRangePicker";
import { ExportButton } from "@/components/reports/ExportButton";
import { FilterBar } from "@/components/reports/FilterBar";
import { InvoicesRevenueSection } from "@/components/reports/InvoicesRevenueSection";
import { EmptyState, MetricCard, ReportHeader } from "@/components/reports/ReportUi";
import { getOffersRevenueReport } from "@/lib/actions/reports-actions";
import { filterLabels, reportFilter, sar, type ReportSearchParams } from "@/lib/reports/filters";

const labels: Record<string, string> = { sent: "مرسلة", accepted: "مقبولة", rejected: "مرفوضة", expired: "منتهية" };
export default async function OffersRevenuePage({ searchParams }: { searchParams: ReportSearchParams }) {
  const filter = reportFilter(searchParams); const data = await getOffersRevenueReport(filter); const rows = data.offers.map((row) => ({ ...row, status: labels[row.status] ?? row.status }));
  return <section className="space-y-6"><ReportHeader title="تقرير العروض والإيرادات" description="حالات العروض وقيم العقود النشطة ومساهمة المندوبين." action={<ExportButton filename="تقرير-العروض-والإيرادات" title="تقرير العروض والإيرادات" filters={filterLabels(filter)} columns={[{ key: "status", label: "الحالة" }, { key: "count", label: "العدد" }, { key: "totalValue", label: "القيمة (ر.س)" }]} rows={rows} summary={{ status: "العقود النشطة", count: data.contracts.count, totalValue: data.contracts.totalValue }} />} /><FilterBar><DateRangePicker value={filter} /></FilterBar><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><MetricCard label="العقود المفعلة" value={data.contracts.count} /><MetricCard label="إجمالي الإيراد" value={sar(data.contracts.totalValue)} /><MetricCard label="متوسط العرض المقبول" value={sar(data.avgOfferValue)} /><MetricCard label="متوسط وقت القرار" value={`${data.avgDecisionTime} يوم`} /></div>{rows.some((row) => row.count) || data.contracts.count ? <><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{rows.map((row) => <MetricCard key={row.status} label={`العروض ${row.status}`} value={row.count} hint={sar(row.totalValue)} />)}</div>{data.repRevenue && <div className="overflow-x-auto rounded-2xl bg-white shadow-sm"><h2 className="p-5 text-lg font-bold text-nebras-green">الإيراد حسب المندوب</h2><table className="w-full text-right"><thead className="bg-nebras-green text-white"><tr><th className="p-4">المندوب</th><th className="p-4">العقود</th><th className="p-4">الإيراد</th></tr></thead><tbody>{data.repRevenue.map((row) => <tr className="border-b last:border-0" key={row.repId}><td className="p-4 font-bold">{row.repName}</td><td className="p-4">{row.contractsCount}</td><td className="p-4">{sar(row.totalRevenue)}</td></tr>)}</tbody></table></div>}</> : <EmptyState />}<InvoicesRevenueSection /></section>;
}
