begin;
select plan(16);
select has_table('public', 'regions', 'regions reference table exists');
select has_table('public', 'cities', 'cities reference table exists');
select has_table('public', 'facilities', 'facilities table exists');
select has_table('public', 'facility_activity', 'facility activity table exists');
select has_column('public', 'companies', 'whatsapp_template', 'company WhatsApp template exists');
select has_index('public', 'facilities', 'idx_facilities_phone_unique_per_company', 'tenant phone uniqueness index exists');
select has_function('public', 'normalize_saudi_phone', array['text'], 'phone normalization helper exists');
select is(public.normalize_saudi_phone('+966 50-123-4567'), '966501234567', 'international phone is normalized');
select is(public.normalize_saudi_phone('0501234567'), '966501234567', 'local phone is normalized');
select is((select count(*)::integer from public.regions), 13, 'all Saudi regions are seeded');
select is((select count(*)::integer from public.cities where name_en = 'Other'), 13, 'each region has an Other city');
set local role authenticated;
select set_config('request.jwt.claims', '{"sub":"dddddddd-dddd-4ddd-8ddd-dddddddddddd","role":"authenticated","user_role":"sales_user","company_id":"11111111-1111-4111-8111-111111111111"}', true);
select is((select count(*)::integer from public.facilities where company_id = '22222222-2222-4222-8222-222222222222'), 0, 'other tenant facilities are invisible');
select is((select count(*)::integer from public.facilities where assigned_to is null), 0, 'unassigned facilities are invisible to Sales Users');
select is((select count(*)::integer from public.facilities where assigned_to <> auth.uid()), 0, 'other owner facilities are invisible to Sales Users');
select throws_ok($$delete from public.facilities where id = '30000000-0000-4000-8000-000000000001'$$, '42501', null, 'hard delete is denied');
reset role;
select set_config('request.jwt.claims', '', true);
select lives_ok($$select count(*) from public.facility_activity$$, 'activity log remains readable to database owner');
select * from finish();
rollback;
