begin;
select plan(7);
select has_table('public', 'offers', 'offers table exists');
select has_table('public', 'offer_line_items', 'offer line items table exists');
select has_type('public', 'offer_status', 'offer status enum exists');
select has_type('public', 'discount_type', 'discount type enum exists');
select has_trigger('public', 'offer_line_items', 'trg_update_offer_subtotal', 'subtotal trigger exists');
select has_trigger('public', 'offers', 'trg_calculate_offer_totals', 'totals trigger exists');
select has_trigger('public', 'offers', 'trg_validate_offer_and_immutability', 'immutability trigger exists');
select * from finish();
rollback;
