import Link from "next/link";
import { getContractsDirectory, type ContractDisplayStatus } from "@/lib/actions/contracts";
import { CONTRACT_STATUS_LABELS } from "@/lib/utils/contracts";
import { ExportButton } from "@/app/(dashboard)/dashboard/facilities/components/ExportButton";

export default async function ContractsPage({ searchParams }: { searchParams?: { status?: string; owner?: string } }) {
  const status = (searchParams?.status ?? "") as ContractDisplayStatus | "";
  const result = await getContractsDirectory({ status, ownerId: searchParams?.owner });
  if (!result.success) return <section dir="rtl"><h1 className="text-3xl font-extrabold text-nebras-green">العقود</h1><p className="mt-6 rounded-xl bg-red-50 p-4 text-red-700">{result.error.message}</p></section>;
  return <section className="space-y-6" dir="rtl"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="font-bold text-nebras-gold">المبيعات</p><h1 className="text-3xl font-extrabold text-nebras-green">العقود</h1></div><ExportButton endpoint="/api/contracts/export" params={searchParams ?? {}} /></div><form className="flex flex-wrap gap-3 rounded-2xl bg-white p-4 shadow-sm"><label className="font-bold">الحالة<select name="status" defaultValue={status} className="mr-2 rounded-xl border bg-white px-3 py-2 font-normal"><option value="">الكل</option>{Object.entries(CONTRACT_STATUS_LABELS).map(([value,label]) => <option key={value} value={value}>{label}</option>)}</select></label>{result.data.canFilterOwner && <label className="font-bold">المسؤول<select name="owner" defaultValue={searchParams?.owner ?? ""} className="mr-2 rounded-xl border bg-white px-3 py-2 font-normal"><option value="">الكل</option>{result.data.owners.map((owner:any) => <option key={owner.id} value={owner.id}>{owner.display_name}</option>)}</select></label>}<button className="rounded-xl bg-nebras-green px-5 py-2 font-bold text-white">تطبيق</button></form>
    <div className="overflow-x-auto rounded-2xl bg-white shadow-sm"><table className="w-full min-w-[900px] text-right"><thead className="bg-slate-50 text-sm"><tr><th className="p-4">العقد</th><th className="p-4">المنشأة</th><th className="p-4">جهة الاتصال</th><th className="p-4">المسؤول</th><th className="p-4">الفترة</th><th className="p-4">الحالة</th><th className="p-4">القيمة</th></tr></thead><tbody>{result.data.contracts.map((contract) => <tr key={contract.id} className="border-t"><td className="p-4"><Link href={`/dashboard/facilities/${contract.facilityId}`} className="font-bold text-nebras-green hover:underline">{contract.referenceNumber}<small className="mr-2">v{contract.version}</small><span className="block font-normal text-slate-600">{contract.title}</span></Link></td><td className="p-4">{contract.facilityName}</td><td className="p-4">{contract.contactName ?? "—"}</td><td className="p-4">{contract.ownerName ?? "—"}</td><td className="p-4">{contract.startDate}<br />{contract.endDate}</td><td className="p-4"><span className="rounded-full bg-slate-100 px-3 py-1 text-sm font-bold">{CONTRACT_STATUS_LABELS[contract.displayStatus]}</span></td><td className="p-4 font-extrabold">{contract.value.toLocaleString("ar-SA",{minimumFractionDigits:2})} ر.س</td></tr>)}</tbody></table>{!result.data.contracts.length && <p className="p-8 text-center text-slate-500">لا توجد عقود مطابقة.</p>}</div><div className="rounded-2xl bg-nebras-green p-5 text-white"><span>إجمالي العقود المفلترة</span><strong className="mr-4 text-2xl text-nebras-gold">{result.data.total.toLocaleString("ar-SA",{minimumFractionDigits:2})} ر.س</strong></div>
  </section>;
}
