with city_seed(region_en, name_ar, name_en) as (
  values
    ('Riyadh', 'الرياض', 'Riyadh'),
    ('Riyadh', 'الدرعية', 'Diriyah'),
    ('Riyadh', 'الخرج', 'Al Kharj'),
    ('Riyadh', 'الدوادمي', 'Al Duwadimi'),
    ('Riyadh', 'المجمعة', 'Al Majmaah'),
    ('Riyadh', 'القويعية', 'Al Quwaiiyah'),
    ('Riyadh', 'الأفلاج', 'Al Aflaj'),
    ('Riyadh', 'وادي الدواسر', 'Wadi Al Dawasir'),
    ('Riyadh', 'الزلفي', 'Al Zulfi'),
    ('Riyadh', 'شقراء', 'Shaqra'),
    ('Riyadh', 'حوطة بني تميم', 'Hawtat Bani Tamim'),
    ('Riyadh', 'عفيف', 'Afif'),
    ('Riyadh', 'السليل', 'As Sulayyil'),
    ('Riyadh', 'ضرما', 'Dharma'),
    ('Riyadh', 'المزاحمية', 'Al Muzahimiyah'),
    ('Riyadh', 'رماح', 'Rumah'),
    ('Riyadh', 'ثادق', 'Thadiq'),
    ('Riyadh', 'حريملاء', 'Huraymila'),
    ('Riyadh', 'الغاط', 'Al Ghat'),
    ('Riyadh', 'مرات', 'Marat'),
    ('Riyadh', 'تمير', 'Tumair'),
    ('Riyadh', 'الأرطاوية', 'Al Artawiyah'),

    ('Makkah', 'مكة المكرمة', 'Makkah'),
    ('Makkah', 'جدة', 'Jeddah'),
    ('Makkah', 'الطائف', 'Taif'),
    ('Makkah', 'القنفذة', 'Al Qunfudhah'),
    ('Makkah', 'الليث', 'Al Lith'),
    ('Makkah', 'رابغ', 'Rabigh'),
    ('Makkah', 'الجموم', 'Al Jumum'),
    ('Makkah', 'الكامل', 'Al Kamil'),
    ('Makkah', 'الخرمة', 'Al Khurmah'),
    ('Makkah', 'رنية', 'Ranyah'),
    ('Makkah', 'تربة', 'Turbah'),
    ('Makkah', 'بحرة', 'Bahrah'),
    ('Makkah', 'خليص', 'Khulais'),
    ('Makkah', 'أضم', 'Adham'),
    ('Makkah', 'العرضيات', 'Al Ardiyat'),
    ('Makkah', 'ميسان', 'Maysan'),

    ('Madinah', 'المدينة المنورة', 'Madinah'),
    ('Madinah', 'ينبع', 'Yanbu'),
    ('Madinah', 'العلا', 'Al Ula'),
    ('Madinah', 'بدر', 'Badr'),
    ('Madinah', 'خيبر', 'Khaybar'),
    ('Madinah', 'مهد الذهب', 'Mahd Al Dhahab'),
    ('Madinah', 'الحناكية', 'Al Hinakiyah'),
    ('Madinah', 'العيص', 'Al Eis'),
    ('Madinah', 'وادي الفرع', 'Wadi Al Fara'),

    ('Al-Qassim', 'بريدة', 'Buraidah'),
    ('Al-Qassim', 'عنيزة', 'Unaizah'),
    ('Al-Qassim', 'الرس', 'Ar Rass'),
    ('Al-Qassim', 'البكيرية', 'Al Bukayriyah'),
    ('Al-Qassim', 'البدائع', 'Al Badayea'),
    ('Al-Qassim', 'المذنب', 'Al Mithnab'),
    ('Al-Qassim', 'رياض الخبراء', 'Riyadh Al Khabra'),
    ('Al-Qassim', 'عيون الجواء', 'Uyun Al Jawa'),
    ('Al-Qassim', 'الشماسية', 'Ash Shimasiyah'),
    ('Al-Qassim', 'عقلة الصقور', 'Uqlat As Suqur'),
    ('Al-Qassim', 'النبهانية', 'An Nabhaniyah'),
    ('Al-Qassim', 'الأسياح', 'Al Asyah'),

    ('Eastern Province', 'الدمام', 'Dammam'),
    ('Eastern Province', 'الخبر', 'Khobar'),
    ('Eastern Province', 'الظهران', 'Dhahran'),
    ('Eastern Province', 'الأحساء', 'Al Ahsa'),
    ('Eastern Province', 'الهفوف', 'Hofuf'),
    ('Eastern Province', 'المبرز', 'Mubarraz'),
    ('Eastern Province', 'القطيف', 'Qatif'),
    ('Eastern Province', 'الجبيل', 'Jubail'),
    ('Eastern Province', 'الخفجي', 'Khafji'),
    ('Eastern Province', 'رأس تنورة', 'Ras Tanura'),
    ('Eastern Province', 'بقيق', 'Abqaiq'),
    ('Eastern Province', 'النعيرية', 'Al Nairiyah'),
    ('Eastern Province', 'حفر الباطن', 'Hafar Al Batin'),
    ('Eastern Province', 'قرية العليا', 'Qaryat Al Ulya'),
    ('Eastern Province', 'الجبيل الصناعية', 'Jubail Industrial City'),

    ('Asir', 'أبها', 'Abha'),
    ('Asir', 'خميس مشيط', 'Khamis Mushait'),
    ('Asir', 'بيشة', 'Bisha'),
    ('Asir', 'محايل عسير', 'Muhayil Aseer'),
    ('Asir', 'أحد رفيدة', 'Ahad Rufaidah'),
    ('Asir', 'سراة عبيدة', 'Sarat Ubaidah'),
    ('Asir', 'رجال ألمع', 'Rijal Almaa'),
    ('Asir', 'النماص', 'Al Namas'),
    ('Asir', 'بلقرن', 'Balqarn'),
    ('Asir', 'تثليث', 'Tathlith'),
    ('Asir', 'ظهران الجنوب', 'Dhahran Al Janub'),
    ('Asir', 'المجاردة', 'Al Majardah'),
    ('Asir', 'تنومة', 'Tanomah'),
    ('Asir', 'بارق', 'Bariq'),
    ('Asir', 'البرك', 'Al Birk'),

    ('Tabuk', 'تبوك', 'Tabuk'),
    ('Tabuk', 'ضباء', 'Duba'),
    ('Tabuk', 'الوجه', 'Al Wajh'),
    ('Tabuk', 'أملج', 'Umluj'),
    ('Tabuk', 'تيماء', 'Tayma'),
    ('Tabuk', 'حقل', 'Haqel'),
    ('Tabuk', 'البدع', 'Al Bad'),

    ('Hail', 'حائل', 'Hail'),
    ('Hail', 'بقعاء', 'Baqa'),
    ('Hail', 'الغزالة', 'Al Ghazalah'),
    ('Hail', 'الشنان', 'Ash Shanan'),
    ('Hail', 'موقق', 'Mawqaq'),
    ('Hail', 'السليمي', 'As Sulaymi'),
    ('Hail', 'سميراء', 'Samira'),
    ('Hail', 'الشملي', 'Ash Shamli'),

    ('Northern Borders', 'عرعر', 'Arar'),
    ('Northern Borders', 'رفحاء', 'Rafha'),
    ('Northern Borders', 'طريف', 'Turaif'),
    ('Northern Borders', 'العويقيلة', 'Al Uwayqilah'),

    ('Jazan', 'جازان', 'Jazan'),
    ('Jazan', 'صبيا', 'Sabya'),
    ('Jazan', 'أبو عريش', 'Abu Arish'),
    ('Jazan', 'صامطة', 'Samtah'),
    ('Jazan', 'بيش', 'Bish'),
    ('Jazan', 'الدرب', 'Ad Darb'),
    ('Jazan', 'أحد المسارحة', 'Ahad Al Masarihah'),
    ('Jazan', 'الطوال', 'At Tuwal'),
    ('Jazan', 'العارضة', 'Al Aridah'),
    ('Jazan', 'ضمد', 'Damad'),
    ('Jazan', 'الريث', 'Ar Rayth'),
    ('Jazan', 'فيفا', 'Fayfa'),
    ('Jazan', 'فرسان', 'Farasan'),
    ('Jazan', 'العيدابي', 'Al Eidabi'),
    ('Jazan', 'هروب', 'Harub'),

    ('Najran', 'نجران', 'Najran'),
    ('Najran', 'شرورة', 'Sharurah'),
    ('Najran', 'حبونا', 'Hubuna'),
    ('Najran', 'بدر الجنوب', 'Badr Al Janub'),
    ('Najran', 'يدمة', 'Yadamah'),
    ('Najran', 'ثار', 'Thar'),
    ('Najran', 'خباش', 'Khubash'),

    ('Al-Baha', 'الباحة', 'Al Baha'),
    ('Al-Baha', 'بلجرشي', 'Baljurashi'),
    ('Al-Baha', 'المخواة', 'Al Makhwah'),
    ('Al-Baha', 'قلوة', 'Qilwah'),
    ('Al-Baha', 'المندق', 'Al Mandaq'),
    ('Al-Baha', 'العقيق', 'Al Aqiq'),
    ('Al-Baha', 'القرى', 'Al Qura'),
    ('Al-Baha', 'الحجرة', 'Al Hajarah'),
    ('Al-Baha', 'بني حسن', 'Bani Hassan'),

    ('Al-Jawf', 'سكاكا', 'Sakaka'),
    ('Al-Jawf', 'دومة الجندل', 'Dumat Al Jandal'),
    ('Al-Jawf', 'القريات', 'Al Qurayyat'),
    ('Al-Jawf', 'طبرجل', 'Tabarjal'),
    ('Al-Jawf', 'صوير', 'Suwayr')
)
insert into public.cities(region_id, name_ar, name_en)
select r.id, s.name_ar, s.name_en
from city_seed s
join public.regions r on r.name_en = s.region_en
where not exists (
  select 1
  from public.cities c
  where c.region_id = r.id
    and c.name_ar = s.name_ar
);
